receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.logical.count:
            enabled: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      process:
        metrics:
          process.open_file_descriptors:
            enabled: true
          process.memory.utilization:
            enabled: true
          process.disk.operations:
            enabled: true
      network:
      processes:
      load:
      disk:
      filesystem:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  resourcedetection:
    detectors: ["system"]
  resource:
    attributes:
    - key: service.name
      action: insert
      value: elastic-otel-docker-test-1

exporters:
  otlphttp:
  # replace with your own endpoint: "https://xxxxxxxxxxxxxxx.apm.us-east-2.aws.elastic-cloud.com:443"
    endpoint: "https://xxxxxxxxxxxxxxx.apm.us-east-2.aws.elastic-cloud.com:443"
    headers: 
  # replace with your own token: "Bearer XXXXXXXXXXXXXXX"
          "Authorization": "Bearer XXXXXXXXXXXXXXX"
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [resource, resourcedetection]
      exporters: [debug, otlphttp]

    traces:
      receivers: [otlp]
      processors: [resource, resourcedetection]
      exporters: [debug, otlphttp]

    logs:
      receivers: [otlp]
      processors: [resource, resourcedetection]
      exporters: [debug, otlphttp]